[platformio]
src_dir = main

[env]
check_flags =
  cppcheck: --suppress=unusedFunction
  cppcheck: --suppress=syntaxError
build_flags =
  -DI2S_BCLK_PIN=5
  -DI2S_WS_PIN=6
  -DI2S_DIN_PIN=7
  ; Feature toggles (override include/elsa_config.h defaults)
  -DENABLE_HAIR_STRIP=1
  -DTEST_SOLID_COLOR=0
  ; -DENABLE_WEB_TELEMETRY=0
  ; -DENABLE_CONFIG_ENDPOINT=0
  ; -DENABLE_WIFI_KEEPALIVE=0
  ; -DENABLE_OTA=1
  -DAUDIO_TASK_ENABLE=1
  -DENABLE_FADE_TO_STARTUP=1
  -DENABLE_BEAT_WAVES=1
  -DENABLE_FALLBACK_WAVES=1
  ; -DDEBUG_BEAT_TIMING=0
  ; -DDEBUG_WAVE_TIMING=0
  -DPROFILE_PERF=0
  -DRENDER_TARGET_FPS=100

[env:esp32-s3-super-mini-idf]
platform = espressif32
board = esp32-s3-super-mini-4m2m
framework = espidf
monitor_speed = 115200
upload_speed = 115200
