[env]
lib_deps =
  fastled/FastLED @ ^3.7.0

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DI2S_BCLK_PIN=5
  -DI2S_WS_PIN=6
  -DI2S_DIN_PIN=7

[env:esp32-s3-super-mini]
platform = espressif32
board = esp32-s3-super-mini-4m2m
framework = arduino
monitor_speed = 115200
upload_speed = 115200
monitor_port = /dev/cu.usbmodem21101
; Upload over USB (default)
upload_protocol = esptool

; OTA upload (optional)
; upload_protocol = espota
; upload_port = 192.168.31.154
; upload_flags =
;   --auth=${sysenv.OTA_PASSWORD}

[env:esp32-s3-super-mini-ota]
platform = espressif32
board = esp32-s3-super-mini-4m2m
framework = arduino
monitor_speed = 115200
upload_speed = 115200
monitor_port = /dev/cu.usbmodem21301
upload_protocol = espota
upload_port = 192.168.31.154
extra_scripts = pre:scripts/ota_from_secrets.py
